name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*.*.*'            # Only trigger on version tags (1.0.0, 1.1.0, etc.)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Needed to update/create GitHub releases
      packages: write  # ✅ Needed to push Docker images

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install tomllib for version extraction
        run: pip install tomli

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          # Use the git tag as version (without 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{tag}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create release notes
        run: |
          echo "## Docker Image Published" >> release_notes.md
          echo "" >> release_notes.md
          echo "Docker image has been published to GitHub Container Registry:" >> release_notes.md
          echo "" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "# Pull and run the image" >> release_notes.md
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}" >> release_notes.md
          echo "docker run --rm -it -v \$(pwd)/media:/app/media ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}" >> release_notes.md
          echo "\`\`\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "Available tags:" >> release_notes.md
          echo "- \`${{ env.VERSION }}\`" >> release_notes.md
          echo "- \`latest\`" >> release_notes.md

          # Add 'latest' only if on default branch
          if [ "${{ github.ref_name }}" = "${{ github.event.repository.default_branch }}" ]; then
            echo "- \`latest\`" >> release_notes.md
          fi

      - name: Update release with Docker info
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}