name: Run Python Tests

permissions:
  contents: read

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install project and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]  # uses pyproject.toml [project.optional-dependencies]

      - name: Run Tests
        run: |
          python -m pytest tests/test_downloader.py
          