name: Update Archive

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  update-archive:
    if: github.ref == 'refs/heads/dev'  # Ensures it runs only on dev branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout smd-docsite repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate archive.md
        run: |
          python docs/generate_archive.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/archive.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update archive.md with latest releases"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
