name: Update Contributors

on:
  workflow_dispatch:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update docs/contributors.md with grouped and timestamped contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          touch docs/contributors.md

          AUTHOR="nayandas69"
          TEMP_FILE=$(mktemp)

          declare -A human_prs
          declare -A bot_prs

          PAGE=1
          while :
          do
            PRS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=dev&per_page=100&page=$PAGE")

            PR_COUNT=$(echo "$PRS" | jq 'length')
            if [ "$PR_COUNT" -eq 0 ]; then break; fi

            echo "$PRS" | jq -r '.[] | select(.merged_at != null) | "\(.user.login)|\(.title)|\(.merged_at)"' |
            while IFS="|" read -r USER TITLE DATE; do
              DATE_FORMATTED=$(date -d "$DATE" +"%Y-%m-%d")
              ENTRY="  - _${TITLE}_ (${DATE_FORMATTED})"
              if [[ "$USER" == *"[bot]"* ]]; then
                bot_prs["$USER"]+=$'\n'"$ENTRY"
              elif [[ "$USER" != "$AUTHOR" ]]; then
                human_prs["$USER"]+=$'\n'"$ENTRY"
              fi
            done

            PAGE=$((PAGE + 1))
          done

          echo "# Contributors" > "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"

          echo "## Author" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          echo "- [**$AUTHOR**](https://github.com/$AUTHOR) — Author and devtainer" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"

          echo "## Human Contributors (via PRs)" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          for USER in "${!human_prs[@]}"; do
            echo "- [**$USER**](https://github.com/$USER)" >> "$TEMP_FILE"
            echo "${human_prs[$USER]}" >> "$TEMP_FILE"
            echo "" >> "$TEMP_FILE"
          done

          echo "## Bot Contributors" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          for BOT in "${!bot_prs[@]}"; do
            echo "- [**$BOT**](https://github.com/$BOT)" >> "$TEMP_FILE"
            echo "${bot_prs[$BOT]}" >> "$TEMP_FILE"
            echo "" >> "$TEMP_FILE"
          done

          echo "---" >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          echo "We sincerely appreciate your efforts in making this project better." >> "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          echo "If you contributed and don’t see your name here, feel free to open a pull request to add yourself!" >> "$TEMP_FILE"

          # Only commit if content differs
          if cmp -s "$TEMP_FILE" docs/contributors.md; then
            echo "Contributors list is already up to date. Skipping commit."
            echo "skip_commit=true" >> $GITHUB_ENV
          else
            cp "$TEMP_FILE" docs/contributors.md
            echo "Contributors list updated."
            echo "skip_commit=false" >> $GITHUB_ENV
          fi

      - name: Commit updated docs/contributors.md if changed
        if: env.skip_commit == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/contributors.md
          git commit -m "Auto-update contributors.md with grouped, timestamped contributors"
          git push origin dev
