name: Update Contributors

on:
  workflow_dispatch:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update docs/CONTRIBUTORS.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          touch docs/CONTRIBUTORS.md

          AUTHOR="nayandas69"

          # Fetch contributors
          CONTRIBUTORS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/contributors | jq -r '.[].login')

          # Prepare sections
          echo "# Contributors" > docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md
          echo "This project exists thanks to the contributions of the following individuals:" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md

          echo "## Author" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md
          echo "- [**$AUTHOR**](https://github.com/$AUTHOR) — Author and devtainer" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md

          echo "## Contributors" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md

          for USER in $CONTRIBUTORS; do
            if [[ "$USER" != "$AUTHOR" && "$USER" != *"[bot]"* ]]; then
              echo "- [**$USER**](https://github.com/$USER)" >> docs/CONTRIBUTORS.md
            fi
          done

          echo "" >> docs/CONTRIBUTORS.md
          echo "## Bot Contributors" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md

          for USER in $CONTRIBUTORS; do
            if [[ "$USER" == *"[bot]"* ]]; then
              echo "- [**$USER**](https://github.com/$USER)" >> docs/CONTRIBUTORS.md
            fi
          done

          echo "" >> docs/CONTRIBUTORS.md
          echo "---" >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md
          echo "We sincerely appreciate your efforts in making this project better." >> docs/CONTRIBUTORS.md
          echo "" >> docs/CONTRIBUTORS.md
          echo "If you contributed and don’t see your name here, feel free to open a pull request to add yourself!" >> docs/CONTRIBUTORS.md

      - name: Commit updated docs/CONTRIBUTORS.md if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet docs/CONTRIBUTORS.md; then
            echo "No changes to docs/CONTRIBUTORS.md"
          else
            git add docs/CONTRIBUTORS.md
            git commit -m "Auto-update docs/CONTRIBUTORS.md with new contributors"
            git push origin dev
          fi
